### ISSUE TITLE
patches needed with bacnet-stack-0.8.3

### ISSUE THREAD

**Issue by ossisyri** [kmtaylor/libbacnet#1]
There is tried to link files which do not exist. Also some files, which is needed by simple examples are not linked in a .so file. 

I needed to add attached patches with bacnet-stack-0.8.3.

[include.patch.txt](https://github.com/kmtaylor/libbacnet/files/316118/include.patch.txt)
[lib.patch.txt](https://github.com/kmtaylor/libbacnet/files/316119/lib.patch.txt)

**Comment by kmtaylor** [comment]
Thanks for that, as I mentioned in the other issue, the scripts here are intended to work with release r2895. I haven't kept them up to date with the current upstream release. If you'd like to do so, please fork this project and update it to work with upstream.

Thanks.
